### ISSUE TITLE
差个64位就是好评！

### ISSUE THREAD

**Issue by bigday** [lhr000lhr/ZhihuDaily#1]
为嘛要$(ARCHS_STANDARD_32_BIT)才可以，这不科学！

**Comment by lhr000lhr** [comment]
编译问题么？  在模拟器和iPhone 5上都没有任何问题。

**Comment by bigday** [comment]
我重新clone了几次，每次pod update完了就是一堆红点，换成32位才能编译通过，你可能一直在你自己机器上用就不会出错。我这里是Xcode 6.1.

**Comment by lhr000lhr** [comment]
实际上 面前里面还没有用到pod 。你把它删了呗。

------------------ 原始邮件 ------------------
发件人: "bigday"notifications@github.com; 
发送时间: 2014年11月13日(星期四) 下午2:40
收件人: "lhr000lhr/ZhihuDaily"ZhihuDaily@noreply.github.com; 
抄送: "任添糖"lee_peter@foxmail.com; 
主题: Re: [ZhihuDaily] 差个64位就是好评！ (#1)

我重新clone了几次，每次pod update完了就是一堆红点，换成32位才能编译通过，你可能一直在你自己机器上用就不会出错。我这里是Xcode 6.1.

**Comment by bigday** [comment]
``` Objective-C
[!] The `ScrollViewWithSegementControll [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

类似这样的问题，虽然很常见，但解决起来也很讨厌，

但这个路径真的是你忘了删啊……

``` Objective-C
ld: warning: directory not found for option '-F/Users/qsheal/Downloads/AMSmoothAlert-master'
```

而且删掉pods 并不能简单粗暴的解决问题，始终绕不过amr音频转换lib不支持64位的问题，等，还是用pod吧，改一改我还能玩……
